### ISSUE TITLE
Polygon boundaries

### ISSUE THREAD

**Issue by pavodev** [john-guerra/d3-force-boundary#6]
Hi,

I was wondering if anyone ever accomplished to bind the nodes inside any polygon. Right now nodes are bound inside a rectangle.

**Comment by john-guerra** [comment]
@fil did some experiments with transport algorightms https://observablehq.com/@fil/disc-transport

**Comment by Fil** [comment]
See also https://observablehq.com/@severo/fill-a-shape-with-circles
